### ISSUE TITLE
Decorators are formatted as a italic font style

### ISSUE THREAD

**Issue by DCBN** [bchiang7/halcyon-vscode#6]
Hi!

I don't know if anyone else encountered this before, but I installed the theme on my windows machine today. Colors and almost all visuals looks pleasing, as expected. However I noticed that while I am using decorators on my classes, they automatically get formatted as an italic style. Example below:

http://puu.sh/zAnnR/e098ce6d0b.png

I tried a few things such as `"editor.colorDecorators": false` and a bunch of other stuff. Is there a way for me to disable this (possibly?) feature?

Thank you in advance!

**Comment by bchiang7** [comment]
Hey! Thanks for pointing this out. I don't work with decorators much so I wasn't aware of this! The cause of this problem is probably because of https://github.com/bchiang7/halcyon-vscode/blob/master/themes/halcyon-color-theme.json#L602. If you want to try changing `font-style` to `normal`, that's my best guess. If you also want to submit a PR to fix this problem feel free as well! If not, let me know and I can push up a fix if this is the root of the problem

**Comment by DCBN** [comment]
Hi again!

I managed to fix the issue with leaving the fontStyle empty, for some reason you're not allowed to give it a normal fontStyle however giving it a an empty string really results in the same way "normal" would.

E.g `"editor.tokenColorCustomizations": {
        "[Halcyon]": {
            "textMateRules": [
                {
                    "name": "Decorators",
                    "scope": [
                        "meta.decorator",
                        "tag.decorator.js entity.name.tag",
                        "tag.decorator.js punctuation.definition.tag"
                    ],
                    "settings": {
                        "fontStyle": "",
                        "foreground": "#5ccfe6"
                    }
                }
            ]
        }
    }`.

**Comment by bchiang7** [comment]
Just released 0.0.9 with this fix
